package com.vochidai.WebTaxi.mapper;

import com.vochidai.WebTaxi.model.Post;
import com.vochidai.WebTaxi.model.PostExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PostMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post
     *
     * @mbg.generated Sat Jun 17 14:21:47 ICT 2023
     */
    long countByExample(PostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post
     *
     * @mbg.generated Sat Jun 17 14:21:47 ICT 2023
     */
    int deleteByExample(PostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post
     *
     * @mbg.generated Sat Jun 17 14:21:47 ICT 2023
     */
    int deleteByPrimaryKey(Integer postId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post
     *
     * @mbg.generated Sat Jun 17 14:21:47 ICT 2023
     */
    int insert(Post row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post
     *
     * @mbg.generated Sat Jun 17 14:21:47 ICT 2023
     */
    int insertSelective(Post row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post
     *
     * @mbg.generated Sat Jun 17 14:21:47 ICT 2023
     */
    List<Post> selectByExampleWithBLOBs(PostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post
     *
     * @mbg.generated Sat Jun 17 14:21:47 ICT 2023
     */
    List<Post> selectByExample(PostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post
     *
     * @mbg.generated Sat Jun 17 14:21:47 ICT 2023
     */
    Post selectByPrimaryKey(Integer postId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post
     *
     * @mbg.generated Sat Jun 17 14:21:47 ICT 2023
     */
    int updateByExampleSelective(@Param("row") Post row, @Param("example") PostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post
     *
     * @mbg.generated Sat Jun 17 14:21:47 ICT 2023
     */
    int updateByExampleWithBLOBs(@Param("row") Post row, @Param("example") PostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post
     *
     * @mbg.generated Sat Jun 17 14:21:47 ICT 2023
     */
    int updateByExample(@Param("row") Post row, @Param("example") PostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post
     *
     * @mbg.generated Sat Jun 17 14:21:47 ICT 2023
     */
    int updateByPrimaryKeySelective(Post row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post
     *
     * @mbg.generated Sat Jun 17 14:21:47 ICT 2023
     */
    int updateByPrimaryKeyWithBLOBs(Post row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post
     *
     * @mbg.generated Sat Jun 17 14:21:47 ICT 2023
     */
    int updateByPrimaryKey(Post row);
}