package com.vochidai.WebTaxi.model;

public class Post {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.post_id
     *
     * @mbg.generated Sat Jun 17 14:21:47 ICT 2023
     */
    private Integer postId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.title
     *
     * @mbg.generated Sat Jun 17 14:21:47 ICT 2023
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.customer_id
     *
     * @mbg.generated Sat Jun 17 14:21:47 ICT 2023
     */
    private Integer customerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.category_id
     *
     * @mbg.generated Sat Jun 17 14:21:47 ICT 2023
     */
    private Integer categoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.content
     *
     * @mbg.generated Sat Jun 17 14:21:47 ICT 2023
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.post_id
     *
     * @return the value of post.post_id
     *
     * @mbg.generated Sat Jun 17 14:21:47 ICT 2023
     */
    public Integer getPostId() {
        return postId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.post_id
     *
     * @param postId the value for post.post_id
     *
     * @mbg.generated Sat Jun 17 14:21:47 ICT 2023
     */
    public void setPostId(Integer postId) {
        this.postId = postId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.title
     *
     * @return the value of post.title
     *
     * @mbg.generated Sat Jun 17 14:21:47 ICT 2023
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.title
     *
     * @param title the value for post.title
     *
     * @mbg.generated Sat Jun 17 14:21:47 ICT 2023
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.customer_id
     *
     * @return the value of post.customer_id
     *
     * @mbg.generated Sat Jun 17 14:21:47 ICT 2023
     */
    public Integer getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.customer_id
     *
     * @param customerId the value for post.customer_id
     *
     * @mbg.generated Sat Jun 17 14:21:47 ICT 2023
     */
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.category_id
     *
     * @return the value of post.category_id
     *
     * @mbg.generated Sat Jun 17 14:21:47 ICT 2023
     */
    public Integer getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.category_id
     *
     * @param categoryId the value for post.category_id
     *
     * @mbg.generated Sat Jun 17 14:21:47 ICT 2023
     */
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.content
     *
     * @return the value of post.content
     *
     * @mbg.generated Sat Jun 17 14:21:47 ICT 2023
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.content
     *
     * @param content the value for post.content
     *
     * @mbg.generated Sat Jun 17 14:21:47 ICT 2023
     */
    public void setContent(String content) {
        this.content = content;
    }
}